spring:
  application:
    name: user-service-consumer
  cloud:
        stream:
          kafka:
            binder:
              autoCreateTopics: false

#   springboot http端口    简单理解为业务的对公端口 比如开放网关
server:
  port: 8080
## Eureka Server 服务 URL,用于客户端注册
eureka:
  client:
    serviceUrl:
      #注册服务器的高可用配置 最终只会注册到其中一台上
      defaultZone: http://localhost:9090/eureka,http://localhost:9091/eureka
    # eureka轮训注册中心获取注册信息的周期  默认30s  http采用拉的方式 无法像zk一样走推
    registry-fetch-interval-seconds: 20
    # 应用自身上报周期  zk是通过会话的心跳保活感知
    instance-info-replication-interval-seconds: 20
  # EurekaClient关联Applications(AbstractQueue<Application>) ，每个Application又关联Set<InstanceInfo>
  instance:
    # 定制服务实例id(即在eureka管理页看到的实例文案，默认${hostname}:${spring.application.name}:${server.port})
    instance-id: ${spring.application.name}:${server.port}
    # 指定在eureka管理该实例时 对应的实例提供的端点信息 默认/info
    status-page-url-path: /health


# 关掉eureka的服务发现，手动指定ribbon的服务列表
#ribbon:
#  eureka:
#    enable: false
#user-service-provider：
#  ribbon:
#    listOfServers: http://localhost:7070,http://localhost:7070

feign:
  hystrix:
    enabled: true
## Management 安全失效
management:
  security:
    enabled: false


